Repository UnitTestBot/UTBotJava, pull requests merged in 2022-09, with the labels that each got.

#856 Fix coverage calculation
  utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt
  utbot-junit-contest/src/main/kotlin/org/utbot/contest/Statistics.kt
Labels: bug

#741 SysReq and minor updates to README added
  README.md
  SystemRequirements.md
Labels: documentation

#906 fix git related issue #905
  .github/workflows/build-and-run-tests-from-branch.yml
Labels: bug

#914 No true branch test is generated for code with String.split(";\\s") #885
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RegexModelProvider.kt
Labels: fuzzing

#931 additional fix of checkout with custom commit sha
  .github/workflows/build-and-run-tests-from-branch.yml
  .github/workflows/publish-on-github-packages.yml
Labels: bug

#861 Contributing guide and related docs updated
  CONTRIBUTING.md
  Conventions.md
  DEVNOTE.md
  SystemRequirements.md
Labels: documentation

#988 Fuzzer should generate tests for simple collection with generic types #875
  utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
  utbot-framework/src/main/kotlin/org/utbot/fuzzer/FuzzerFunctions.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzedMethodDescription.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzedType.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Fuzzer.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/objects/AssembleModelUtils.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ArrayModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/CollectionModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/CollectionWithEmptyStatesModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/CollectionWithModificationModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ConstantsModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/DateConstantModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/NumberClassModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ObjectModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/PrimitiveRandomModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RecursiveModelProvider.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/CollectionModelProviderTest.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/ModelProviderTest.kt
Labels: fuzzing
