Repository UnitTestBot/UTBotJava, pull requests merged in 2022-08, with the labels that each got.

#624 Generate DisplayName annotation only for JUnit 5 #576
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/TestFrameworkManager.kt
Labels: meta generator

#685 Updated Readme content
  README.md
Labels: documentation

#713 Mutate values to improve code coverage #213
  utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
  utbot-framework/src/main/kotlin/org/utbot/fuzzer/FuzzerFunctions.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzedValue.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Fuzzer.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzerStatistics.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/ModelMutator.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/RandomExtensions.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/NumberRandomMutator.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/StringConstantModelProvider.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/ModelMutatorTest.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/ModelProviderTest.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/RandomExtensionsTest.kt
Labels: fuzzing

#585 Introduce custom JavaDoc tags #565
  utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
  utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/tree/CgElement.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgAbstractRenderer.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/CgVisitor.kt
  utbot-framework/src/test/kotlin/org/utbot/examples/UtValueTestCaseChecker.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtCustomJavaDocTagProvider.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/javadoc/UtDocumentationProvider.kt
  utbot-intellij/src/main/resources/META-INF/plugin.xml
  utbot-summary-tests/src/test/kotlin/examples/CustomJavaDocTagsEnabler.kt
  utbot-summary-tests/src/test/kotlin/examples/controlflow/SummaryConditionsTest.kt
  utbot-summary-tests/src/test/kotlin/examples/exceptions/SummaryExceptionClusteringExamplesTest.kt
  utbot-summary-tests/src/test/kotlin/examples/structures/SummaryMinStackTest.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocComment.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocCommentBuilder.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/comment/CustomJavaDocTagProvider.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/comment/SimpleClusterCommentBuilder.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/comment/SimpleCommentBuilder.kt
  utbot-summary/src/test/kotlin/org/utbot/summary/comment/SimpleCommentBuilderTest.kt
Labels: meta generator

#793 Use regex for generating string when regex pattern is found #778
  utbot-framework/src/main/kotlin/org/utbot/fuzzer/FuzzerFunctions.kt
  utbot-fuzzers/build.gradle
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzedConcreteValue.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzedContext.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzedMethodDescription.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzedValue.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Fuzzer.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/ModelMutator.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/RegexStringModelMutator.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/mutators/StringRandomMutator.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ConstantsModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/RegexModelProvider.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/FuzzedValueDescriptionTest.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/ModelProviderTest.kt
Labels: fuzzing
