Repository UnitTestBot/UTBotJava, pull requests merged in 2022-11, with the labels that each got.

#1189 UtUtils class -- doc added #930
  docs/UtUtilsClass.md
Labels: documentation

#1375 Demo link updated in Readme.md
  README.md
Labels: documentation

#1387 Doc structure revision
  CONTRIBUTING.md
  SystemRequirements.md
  docs/ci/ci-in-utbot-java.md
  docs/ci/docker-for-utbot-java.md
  docs/ci/ssh-session-with-github-agent.md
  docs/contributing/Conventions.md
  docs/contributing/InterProcessDebugging.md
  docs/contributing/LabelUsageGuideline.md
Labels: documentation

#877 Design document for problems and solutions for static initializers analysis
  docs/StaticInitializersAnalysis.md
Labels: documentation, engine

#1374 Minor updates to UtUtilsClass docs
  docs/UtUtilsClass.md
Labels: documentation

#1417 CodeGenerationAndRendering doc added
  docs/CodeGenerationAndRendering.md
Labels: documentation

#1422 Intellij IDEA IU plugin size fix
  utbot-intellij-js/src/main/kotlin/org/utbot/intellij/plugin/language/js/JsTestsModel.kt
  utbot-js/build.gradle.kts
  utbot-js/src/main/kotlin/api/JsTestGenerator.kt
  utbot-js/src/main/kotlin/codegen/JsCodeGenerator.kt
  utbot-js/src/main/kotlin/framework/codegen/JsCgLanguageAssistant.kt
  utbot-js/src/main/kotlin/framework/codegen/JsDomain.kt
  utbot-js/src/main/kotlin/framework/codegen/JsTestFrameworkManager.kt
  utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsCgCallableAccessManager.kt
  utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsCgMethodConstructor.kt
  utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsCgStatementConstructor.kt
  utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsCgVariableConstructor.kt
  utbot-js/src/main/kotlin/framework/codegen/model/constructor/tree/JsTestFrameworkManager.kt
  utbot-js/src/main/kotlin/framework/codegen/model/constructor/visitor/CgJsRenderer.kt
  utbot-js/src/main/kotlin/parser/IAstVisitor.kt
  utbot-js/src/main/kotlin/parser/JsClassAstVisitor.kt
  utbot-js/src/main/kotlin/parser/JsFunctionAstVisitor.kt
  utbot-js/src/main/kotlin/parser/JsFuzzerAstVisitor.kt
  utbot-js/src/main/kotlin/parser/JsParserUtils.kt
  utbot-js/src/main/kotlin/parser/JsToplevelFunctionAstVisitor.kt
  utbot-js/src/main/kotlin/service/BasicCoverageService.kt
  utbot-js/src/main/kotlin/service/CoverageServiceProvider.kt
  utbot-js/src/main/kotlin/service/ServiceContext.kt
  utbot-js/src/main/kotlin/service/TernService.kt
  utbot-js/src/main/kotlin/utils/JsClassConstructors.kt
  utbot-js/src/main/kotlin/utils/ValueUtil.kt
Labels: JavaScript

#1440 Unit testing requirement added
  .github/pull_request_template.md
Labels: documentation

#1443 Testing requirement added
  CONTRIBUTING.md
Labels: documentation
