Repository UnitTestBot/UTBotJava, pull requests merged in 2022-07, with the labels that each got.

#450 Removed always used coverage-based minimization strategy for plugin
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/CodeGenerator.kt
Labels: bug, engine

#444 Add summary tests for ListWrapperReturnsVoidExample
  utbot-summary-tests/src/test/kotlin/examples/collections/SummaryListWrapperReturnsVoidTest.kt
Labels: meta generator

#480 Optimized dependencies
  utbot-framework/build.gradle
  utbot-intellij/build.gradle
Labels: infrastructure

#515 Generate test by fuzzing for methods with no parameters #511
  utbot-framework/src/main/kotlin/org/utbot/engine/UtBotSymbolicEngine.kt
  utbot-framework/src/main/kotlin/org/utbot/external/api/UtBotJavaApi.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/FuzzedParameter.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/Fuzzer.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/ModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/AbstractModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ArrayModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/CharToStringModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/CollectionModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ConstantsModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/EnumModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/NullModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/ObjectModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/PrimitiveDefaultsModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/PrimitiveWrapperModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/PrimitivesModelProvider.kt
  utbot-fuzzers/src/main/kotlin/org/utbot/fuzzer/providers/StringConstantModelProvider.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/FuzzedValueDescriptionTest.kt
  utbot-fuzzers/src/test/kotlin/org/utbot/framework/plugin/api/ModelProviderTest.kt
Labels: fuzzing

#476 Provide references to invoked methods in summary
  utbot-framework/src/test/kotlin/org/utbot/examples/algorithms/SortTest.kt
  utbot-summary-tests/src/test/kotlin/examples/algorithms/SummaryReturnExampleTest.kt
  utbot-summary-tests/src/test/kotlin/examples/collections/SummaryListWrapperReturnsVoidTest.kt
  utbot-summary-tests/src/test/kotlin/examples/controlflow/SummaryCycleTest.kt
  utbot-summary-tests/src/test/kotlin/examples/inner/SummaryInnerCallsTest.kt
  utbot-summary-tests/src/test/kotlin/examples/inner/SummaryNestedCallsTest.kt
  utbot-summary-tests/src/test/kotlin/examples/ternary/SummaryTernaryTest.kt
  utbot-summary-tests/src/test/kotlin/math/SummaryIntMathTest.kt
  utbot-summary-tests/src/test/kotlin/math/SummaryOfMathTest.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/comment/SimpleClusterCommentBuilder.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/comment/SimpleCommentBuilder.kt
Labels: meta generator

#532 Removed external library and added clustering algorithm
  utbot-summary/build.gradle
  utbot-summary/src/main/kotlin/org/utbot/summary/UtSummarySettings.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/clustering/ExecutionMetric.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/clustering/MatrixUniqueness.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/clustering/dbscan/DBSCANModel.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/clustering/dbscan/DBSCANTrainer.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/clustering/dbscan/Metric.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/clustering/dbscan/neighbor/LinearRangeQuery.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/clustering/dbscan/neighbor/Neighbor.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/clustering/dbscan/neighbor/RangeQuery.kt
  utbot-summary/src/test/kotlin/org/utbot/summary/clustering/dbscan/DBSCANTrainerTest.kt
Labels: meta generator

#569 Optimized module dependencies
  gradle.properties
  utbot-core/src/main/kotlin/org/utbot/common/FileUtil.kt
  utbot-framework/build.gradle
  utbot-framework/src/main/kotlin/org/utbot/engine/selectors/strategies/GraphViz.kt
  utbot-framework/src/test/kotlin/org/utbot/framework/codegen/CompilationAndRunUtils.kt
  utbot-junit-contest/build.gradle
  utbot-junit-contest/src/main/kotlin/org/utbot/contest/Contest.kt
  utbot-junit-contest/src/main/kotlin/org/utbot/contest/TestClassWriter.kt
  utbot-sample/build.gradle
Labels: infrastructure

#564 Naming conventions added
  CONTRIBUTING.md
Labels: documentation

#514 Added links to utbot.org and JB Marketplace
  README.md
Labels: documentation
