Repository UnitTestBot/UTBotJava, pull requests merged in 2022-10, with the labels that each got.

#998 Gradle cache usage added
  .github/workflows/build-and-run-tests-from-branch.yml
  .github/workflows/combined-projects-matrix.json
  .github/workflows/framework-tests-matrix.json
Labels: enhancement

#1113 Minor doc updates: SysReq, UI labels, contacts, links to user guide, RD
  CONTRIBUTING.md
  DEVNOTE.md
  README.md
  SystemRequirements.md
  docs/RD for UnitTestBot.md
Labels: documentation

#1229 Supported assemble models for streams in concrete execution
  utbot-core/src/main/kotlin/org/utbot/common/HackUtil.kt
  utbot-core/src/main/kotlin/org/utbot/common/KClassUtil.kt
  utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
  utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/UtExecutionResult.kt
  utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/util/IdUtil.kt
  utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/visible/UtStreamConsumingException.kt
  utbot-framework-test/src/test/kotlin/org/utbot/examples/casts/CastExampleTest.kt
  utbot-framework-test/src/test/kotlin/org/utbot/examples/stream/BaseStreamExampleTest.kt
  utbot-framework-test/src/test/kotlin/org/utbot/examples/stream/DoubleStreamExampleTest.kt
  utbot-framework-test/src/test/kotlin/org/utbot/examples/stream/IntStreamExampleTest.kt
  utbot-framework-test/src/test/kotlin/org/utbot/examples/stream/LongStreamExampleTest.kt
  utbot-framework-test/src/test/kotlin/org/utbot/examples/stream/StreamsAsMethodResultExampleTest.kt
  utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtDoubleStream.java
  utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtIntStream.java
  utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtLongStream.java
  utbot-framework/src/main/java/org/utbot/engine/overrides/stream/UtStream.java
  utbot-framework/src/main/kotlin/org/utbot/engine/Resolver.kt
  utbot-framework/src/main/kotlin/org/utbot/engine/StreamWrappers.kt
  utbot-framework/src/main/kotlin/org/utbot/engine/TypeResolver.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/builtin/UtilMethodBuiltins.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/context/CgContext.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgCallableAccessManager.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/constructor/tree/CgMethodConstructor.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/model/visitor/UtilMethods.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/concrete/StreamConstructors.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtAssembleModelConstructors.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtExecutionInstrumentation.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/concrete/UtModelConstructor.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/util/SootUtils.kt
  utbot-sample/src/main/java/org/utbot/examples/stream/BaseStreamExample.java
  utbot-sample/src/main/java/org/utbot/examples/stream/DoubleStreamExample.java
  utbot-sample/src/main/java/org/utbot/examples/stream/IntStreamExample.java
  utbot-sample/src/main/java/org/utbot/examples/stream/LongStreamExample.java
  utbot-sample/src/main/java/org/utbot/examples/stream/StreamsAsMethodResultExample.java
  utbot-summary/src/main/kotlin/org/utbot/summary/Summarization.kt
  utbot-summary/src/main/kotlin/org/utbot/summary/TagGenerator.kt
Labels: codegen
