Repository UnitTestBot/UTBotJava, pull requests merged in 2023-04, with the labels that each got.

#2087 Support Spring projects with main xml config in utbot-spring-analyzer
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/ApplicationRunner.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/analyzers/SpringApplicationAnalyzer.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/config/TestApplicationConfiguration.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/configurators/ApplicationConfigurator.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/configurators/ApplicationType.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/data/ApplicationData.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/utils/FakeFileManager.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/utils/PathsUtils.kt
Labels: ctg-enhancement, comp-spring

#2089 Patch plugin.xml to declare nightly builds compatible with IDEA 231.*
  gradle.properties
  utbot-intellij/build.gradle.kts
Labels: ctg-enhancement, comp-ide

#2056 Go. Support for all user-defined types
  utbot-go/go-samples/simple/samples_go_ut_test.go
  utbot-go/go-samples/simple/supported_types.go
  utbot-go/go-samples/simple/supported_types_go_ut_test.go
  utbot-go/src/main/kotlin/org/utbot/go/GoLanguage.kt
  utbot-go/src/main/kotlin/org/utbot/go/api/GoTypesApi.kt
  utbot-go/src/main/kotlin/org/utbot/go/api/GoUtModelsApi.kt
  utbot-go/src/main/kotlin/org/utbot/go/api/util/GoTypesApiUtil.kt
  utbot-go/src/main/kotlin/org/utbot/go/api/util/GoUtModelsApiUtil.kt
  utbot-go/src/main/kotlin/org/utbot/go/framework/api/go/GoApi.kt
  utbot-go/src/main/kotlin/org/utbot/go/fuzzer/providers/GoNamedValueProvider.kt
  utbot-go/src/main/kotlin/org/utbot/go/fuzzer/providers/GoNilValueProvider.kt
  utbot-go/src/main/kotlin/org/utbot/go/gocodeanalyzer/AnalysisResults.kt
  utbot-go/src/main/kotlin/org/utbot/go/imports/GoImportsResolver.kt
  utbot-go/src/main/kotlin/org/utbot/go/simplecodegeneration/GoTestCasesCodeGenerator.kt
  utbot-go/src/main/kotlin/org/utbot/go/simplecodegeneration/GoUtModelToCodeConverter.kt
  utbot-go/src/main/kotlin/org/utbot/go/worker/GoCodeTemplates.kt
  utbot-go/src/main/kotlin/org/utbot/go/worker/GoWorkerCodeGenerationHelper.kt
  utbot-go/src/main/kotlin/org/utbot/go/worker/RawExecutionResults.kt
  utbot-go/src/main/resources/go_source_code_analyzer/analysis_results.go
  utbot-go/src/main/resources/go_source_code_analyzer/analyzer_core.go
Labels: ctg-enhancement, lang-go

#2091 CgContext is not a data class!!!
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/CodeGenerator.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/context/CgContext.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgComponents.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringVariableConstructor.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgVariableConstructor.kt
  utbot-js/src/main/kotlin/codegen/JsCodeGenerator.kt
Labels: comp-codegen, ctg-bug-fix

#2090 Support separators in Spring Config Selection ComboBox
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
  utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/models/BaseTestModel.kt
Labels: ctg-enhancement, comp-ui

#2095 Specify explicit foreground color for "GotItMessage"
  utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt
Labels: comp-ide, ctg-bug-fix

#2099 Allow non-unique names in list of classes
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
Labels: comp-ui, comp-ide, ctg-bug-fix

#2102 Support subfolder XML search
  utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/models/BaseTestModel.kt
Labels: ctg-enhancement, comp-spring

#2094 Get rid of maxversion for Mockito library
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/ExternalLibraryDescriptors.kt
Labels: comp-ide, ctg-bug-fix

#2096 Improve the appearance of paths in Spring Config Selection ComboBox
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/util/SpringConfigurationsHelper.kt
Labels: ctg-enhancement, comp-ui, comp-spring

#2114 Go. Maps support
  utbot-go/go-samples/simple/samples_go_ut_test.go
  utbot-go/go-samples/simple/supported_types.go
  utbot-go/go-samples/simple/supported_types_go_ut_test.go
  utbot-go/src/main/kotlin/org/utbot/go/GoEngine.kt
  utbot-go/src/main/kotlin/org/utbot/go/GoLanguage.kt
  utbot-go/src/main/kotlin/org/utbot/go/api/GoTypesApi.kt
  utbot-go/src/main/kotlin/org/utbot/go/api/GoUtModelsApi.kt
  utbot-go/src/main/kotlin/org/utbot/go/api/util/GoTypesApiUtil.kt
  utbot-go/src/main/kotlin/org/utbot/go/api/util/GoUtModelsApiUtil.kt
  utbot-go/src/main/kotlin/org/utbot/go/fuzzer/providers/GoMapValueProvider.kt
  utbot-go/src/main/kotlin/org/utbot/go/fuzzer/providers/GoNilValueProvider.kt
  utbot-go/src/main/kotlin/org/utbot/go/gocodeanalyzer/AnalysisResults.kt
  utbot-go/src/main/kotlin/org/utbot/go/logic/GoTestCasesGenerator.kt
  utbot-go/src/main/kotlin/org/utbot/go/simplecodegeneration/GoUtModelToCodeConverter.kt
  utbot-go/src/main/kotlin/org/utbot/go/worker/GoCodeTemplates.kt
  utbot-go/src/main/kotlin/org/utbot/go/worker/GoWorkerCodeGenerationHelper.kt
  utbot-go/src/main/kotlin/org/utbot/go/worker/RawExecutionResults.kt
  utbot-go/src/main/resources/go_source_code_analyzer/analysis_results.go
  utbot-go/src/main/resources/go_source_code_analyzer/analyzer_core.go
Labels: ctg-enhancement, lang-go

#2118 Update source code compatibility with IDEA 2023.1 API
  gradle.properties
  utbot-intellij-js/src/main/kotlin/org/utbot/intellij/plugin/language/js/JsDialogProcessor.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/inspection/UnitTestBotInspectionTool.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/settings/SettingsWindow.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
  utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/ui/Notifications.kt
Labels: ctg-enhancement, comp-ide

#2122 Enlarge compile scope for Spring projects
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
Labels: ctg-enhancement, comp-spring

#2124 Fix not defined variables in test method in Spring project
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringTestClassConstructor.kt
Labels: comp-codegen, ctg-bug-fix, comp-spring

#2126 Use more safe approach to analyze Spring xml configs
  utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/models/BaseTestModel.kt
Labels: comp-ui, ctg-bug-fix

#2110 Make obtaining Spring beans a little more safe
  utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
Labels: ctg-enhancement, comp-symbolic-engine

#2101 Python codegen improvement: timeouted tests and exceptions
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgMethodConstructor.kt
  utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/PythonDialogProcessor.kt
  utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/PythonDialogWindow.kt
  utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/PythonTestsModel.kt
  utbot-python/src/main/kotlin/org/utbot/python/PythonEngine.kt
  utbot-python/src/main/kotlin/org/utbot/python/PythonTestCaseGenerator.kt
  utbot-python/src/main/kotlin/org/utbot/python/PythonTestGenerationProcessor.kt
  utbot-python/src/main/kotlin/org/utbot/python/evaluation/UtExecutorThread.kt
  utbot-python/src/main/kotlin/org/utbot/python/framework/api/python/PythonApi.kt
  utbot-python/src/main/kotlin/org/utbot/python/framework/api/python/util/PythonIdUtils.kt
  utbot-python/src/main/kotlin/org/utbot/python/framework/codegen/model/PythonDomain.kt
  utbot-python/src/main/kotlin/org/utbot/python/framework/codegen/model/constructor/tree/PythonCgMethodConstructor.kt
  utbot-python/src/main/kotlin/org/utbot/python/framework/codegen/model/constructor/tree/PythonTestFrameworkManager.kt
  utbot-python/src/main/kotlin/org/utbot/python/framework/codegen/model/constructor/visitor/CgPythonRenderer.kt
  utbot-python/src/main/kotlin/org/utbot/python/framework/codegen/model/constructor/visitor/CgPythonVisitor.kt
  utbot-python/src/main/kotlin/org/utbot/python/framework/codegen/model/tree/CgPythonElement.kt
  utbot-python/src/main/kotlin/org/utbot/python/fuzzing/provider/ReduceValueProvider.kt
Labels: ctg-enhancement, comp-codegen, lang-python

#2136 Fix *test/resources* directory creation
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
Labels: comp-ui, ctg-bug-fix

#2125 Use user classpath and Spring Boot in `utbot-spring-analyzer`
  utbot-framework-api/src/main/kotlin/org/utbot/framework/UtSettings.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/process/EngineProcessMain.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/process/generated/EngineProcessModel.Generated.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/GenerateTestsModel.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/process/EngineProcess.kt
  utbot-rd/src/main/rdgen/org/utbot/rd/models/EngineProcessModel.kt
  utbot-rd/src/main/rdgen/org/utbot/rd/models/SpringAnalyzerModel.kt
  utbot-spring-analyzer/build.gradle.kts
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/ApplicationRunner.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/analyzers/SpringApplicationAnalyzer.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/api/ApplicationData.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/configurators/ApplicationConfigurator.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/configurators/PropertiesConfigurator.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/configurators/XmlFilesConfigurator.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/data/ApplicationData.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/generated/SpringAnalyzerProcessModel.Generated.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/postProcessors/UtBotBeanFactoryPostProcessor.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcess.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcessMain.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/utils/ConfigurationManager.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/utils/FakeFileManager.kt
Labels: ctg-enhancement, comp-spring

#2139 Move action update to background thread
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/actions/GenerateTestsAction.kt
Labels: comp-ide, ctg-bug-fix

#2146 Remove accidental Python SDK usage in `UtTestsDialogProcessor`
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
Labels: ctg-bug-fix, comp-spring

#2145 Fix filtering internal calls in sarif stacktrace
  utbot-framework/src/main/kotlin/org/utbot/sarif/SarifReport.kt
Labels: comp-sarif, ctg-bug-fix

#2148 Add RunReadAction wrapper for slow Spring operation
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
Labels: comp-ui, ctg-bug-fix, comp-spring

#2151 Fix models comparison in Spring variable constructor.
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/tree/CgSpringVariableConstructor.kt
Labels: comp-codegen, ctg-bug-fix, comp-spring

#2154 Make loading Spring bean classes even more safe
  utbot-framework-api/src/main/kotlin/org/utbot/framework/plugin/api/Api.kt
Labels: ctg-enhancement, comp-symbolic-engine, comp-spring

#2157 Fix StackOverflow errors in models with mocks processing
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/MockFrameworkManager.kt
  utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/instrumentation/execution/constructors/MockValueConstructor.kt
Labels: comp-codegen, comp-instrumented-process, ctg-bug-fix

#2163 Try to ignore dtd references in xml configs parsing
  utbot-ui-commons/src/main/kotlin/org/utbot/intellij/plugin/models/BaseTestModel.kt
Labels: ctg-bug-fix, comp-spring

#2168 Easy bug template added to github issue templates
  .github/ISSUE_TEMPLATE/bug_report_easy.md
Labels: comp-infrastructure, ctg-qa

#2173 Add Spring config to files to compile
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
Labels: ctg-bug-fix, comp-spring

#2174 Activate selected profiles in Spring
  utbot-framework/src/main/kotlin/org/utbot/framework/process/EngineProcessMain.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/process/generated/EngineProcessModel.Generated.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/process/EngineProcess.kt
  utbot-rd/src/main/rdgen/org/utbot/rd/models/EngineProcessModel.kt
  utbot-rd/src/main/rdgen/org/utbot/rd/models/SpringAnalyzerModel.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/api/ApplicationData.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/configurators/ApplicationConfigurator.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/generated/SpringAnalyzerProcessModel.Generated.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcess.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcessMain.kt
Labels: ctg-enhancement, comp-rd, comp-spring

#2165 Optimize imports programmatically if UtBot is run as a plugin
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/CodeGenerationController.kt
Labels: ctg-enhancement, comp-codegen

#2176 Avoid fully qualified names rendering in mockedConstruction
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/services/framework/MockFrameworkManager.kt
Labels: ctg-enhancement, comp-codegen

#2172 Stop using Spring Boot for pure Spring applications
  utbot-spring-analyzer/build.gradle.kts
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/analyzers/PureSpringApplicationAnalyzer.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/analyzers/SpringApplicationAnalyzer.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/analyzers/SpringApplicationAnalyzerFacade.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/analyzers/SpringBootApplicationAnalyzer.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/configurators/ApplicationConfigurator.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/exception/UtBotSpringShutdownException.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/loggers/RDApacheCommonsLogFactory.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/postProcessors/UtBotBeanFactoryPostProcessor.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcess.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcessMain.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/utils/EnvironmentFactory.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/utils/SourceFinder.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/utils/TempFileManager.kt
Labels: ctg-enhancement, comp-spring

#2137 Enable Fuzzer in Spring no-config test generation
  utbot-framework/src/main/kotlin/org/utbot/framework/plugin/api/TestFlow.kt
  utbot-framework/src/main/kotlin/org/utbot/framework/process/EngineProcessMain.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
Labels: ctg-enhancement, comp-spring

#2183 Support profiles selection for Spring-guided test generation
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/generator/UtTestsDialogProcessor.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/models/GenerateTestsModel.kt
  utbot-intellij/src/main/kotlin/org/utbot/intellij/plugin/ui/GenerateTestsDialogWindow.kt
Labels: ctg-enhancement, comp-ui, comp-spring

#2178 Make spring-analyzer bean post processor distinguish 3 kinds of beans: @Component-like beans, @Bean-like beans, and XML-like beans
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/postProcessors/UtBotBeanFactoryPostProcessor.kt
Labels: ctg-enhancement, comp-spring

#2180 Stop logging useless trace to `LoggerModel.setup`
  utbot-instrumentation/src/main/kotlin/org/utbot/instrumentation/rd/InstrumentedProcess.kt
  utbot-rd/src/main/kotlin/org/utbot/rd/loggers/UtRdKLogger.kt
  utbot-rd/src/main/kotlin/org/utbot/rd/loggers/UtRdLogUtil.kt
  utbot-spring-analyzer/src/main/kotlin/org/utbot/spring/process/SpringAnalyzerProcess.kt
Labels: comp-logging, ctg-bug-fix

#2185 Fix unwanted fields in test class for Spring
  utbot-framework/src/main/kotlin/org/utbot/framework/codegen/domain/models/builders/SpringTestClassModelBuilder.kt
Labels: comp-codegen, ctg-bug-fix, comp-spring

#2184 Remember selections in python dialog
  utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/PythonDialogProcessor.kt
  utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/PythonDialogWindow.kt
  utbot-intellij-python/src/main/kotlin/org/utbot/intellij/plugin/language/python/settings/Settings.kt
Labels: comp-ui, lang-python, ctg-bug-fix
